services:
  database:
    image: postgres:latest
    container_name: tum-ects-database
    environment:
      - POSTGRES_PASSWORD=postgres
  crawler:
    build:
      context: ./crawler
    container_name: tum-ects-crawler
    environment:
      - MAX_WORKERS=1
      - DATABASE_PORT=5432
    depends_on:
      - "database"
  api:
    build:
      context: ./api
    container_name: tum-ects-api
    ports:
      # <exposed port>:5000
      - 5000:5000
    environment:
      - DATABASE_PORT=5432
    depends_on:
      - "mongodb"
