services:
  database:
    image: postgres:latest
    container_name: tum-ects-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  crawler:
    build:
      dockerfile: Dockerfile.crawler
    container_name: tum-ects-crawler
    environment:
      - MAX_WORKERS=1
      - DATABASE_PORT=5432
      - WAIT_HOSTS=database:5432
    depends_on:
      - "database"
  api:
    build:
      dockerfile: Dockerfile.api
    container_name: tum-ects-api
    ports:
      # <exposed port>:5000
      - 5000:5000
    environment:
      - DATABASE_PORT=5432
      - WAIT_HOSTS=database:5432
    depends_on:
      - "database"
      - "crawler"
