services:
  mongodb:
    image: mongo:4.4.9
    ports:
      - 27017:27017
  parser:
    build:
      context: ./parser
    network_mode: "host"
    depends_on:
      - "mongodb"
  api:
    build:
      context: ./api
    network_mode: "host"
    depends_on:
      - "mongodb"
