services:
  database:
    image: mysql:latest
    container_name: tum-ects-database
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=database
  crawler:
    build:
      dockerfile: Dockerfile.crawler
      context: .
    container_name: tum-ects-crawler
    environment:
      - MAX_WORKERS=1
      - DATABASE_PORT=3306
      - WAIT_HOSTS=database:3306
    depends_on:
      - "database"
  api:
    build:
      dockerfile: Dockerfile.api
      context: .
    container_name: tum-ects-api
    ports:
      # <exposed port>:5000
      - 5000:5000
    environment:
      - DATABASE_PORT=3306
      - WAIT_HOSTS=database:3306
    depends_on:
      - "database"
      - "crawler"
