# Generated by ariadne-codegen on 2023-06-07 16:48

from .async_base_client import AsyncBaseClient
from .base_model import BaseModel
from .client import Client
from .exceptions import (
    GraphQLClientError,
    GraphQLClientGraphQLError,
    GraphQLClientGraphQLMultiError,
    GraphQLClientHttpError,
    GraphQlClientInvalidResponseError,
)
from .get_degree_by_i_d import (
    GetDegreeByID,
    GetDegreeByIDDegree,
    GetDegreeByIDDegreeModules,
    GetDegreeByIDDegreeModulesModule,
)
from .get_module_by_i_d import GetModuleByID, GetModuleByIDModule
from .input_types import (
    DegreeInput,
    ModuleInformationInput,
    ModuleInput,
    ModuleMappingInput,
)
from .update_degree import UpdateDegree, UpdateDegreeUpdateDegree
from .update_module import UpdateModule, UpdateModuleUpdateModule

__all__ = [
    "AsyncBaseClient",
    "BaseModel",
    "Client",
    "DegreeInput",
    "GetDegreeByID",
    "GetDegreeByIDDegree",
    "GetDegreeByIDDegreeModules",
    "GetDegreeByIDDegreeModulesModule",
    "GetModuleByID",
    "GetModuleByIDModule",
    "GraphQLClientError",
    "GraphQLClientGraphQLError",
    "GraphQLClientGraphQLMultiError",
    "GraphQLClientHttpError",
    "GraphQlClientInvalidResponseError",
    "ModuleInformationInput",
    "ModuleInput",
    "ModuleMappingInput",
    "UpdateDegree",
    "UpdateDegreeUpdateDegree",
    "UpdateModule",
    "UpdateModuleUpdateModule",
]
