# Generated by ariadne-codegen on 2023-06-07 10:25

from .async_base_client import AsyncBaseClient
from .base_model import BaseModel
from .client import Client
from .exceptions import (
    GraphQLClientError,
    GraphQLClientGraphQLError,
    GraphQLClientGraphQLMultiError,
    GraphQLClientHttpError,
    GraphQlClientInvalidResponseError,
)
from .get_degree_by_i_d import (
    GetDegreeByID,
    GetDegreeByIDDegree,
    GetDegreeByIDDegreeModules,
    GetDegreeByIDDegreeModulesModule,
)
from .get_module_by_i_d import (
    GetModuleByID,
    GetModuleByIDModule,
    GetModuleByIDModuleInformationDe,
    GetModuleByIDModuleInformationEn,
)
from .input_types import (
    DegreeInput,
    ModuleInformationInput,
    ModuleInput,
    ModuleMappingInput,
)
from .update_degree import UpdateDegree, UpdateDegreeUpdateDegree
from .update_module import (
    UpdateModule,
    UpdateModuleUpdateModule,
    UpdateModuleUpdateModuleInformationDe,
    UpdateModuleUpdateModuleInformationEn,
)

__all__ = [
    "AsyncBaseClient",
    "BaseModel",
    "Client",
    "DegreeInput",
    "GetDegreeByID",
    "GetDegreeByIDDegree",
    "GetDegreeByIDDegreeModules",
    "GetDegreeByIDDegreeModulesModule",
    "GetModuleByID",
    "GetModuleByIDModule",
    "GetModuleByIDModuleInformationDe",
    "GetModuleByIDModuleInformationEn",
    "GraphQLClientError",
    "GraphQLClientGraphQLError",
    "GraphQLClientGraphQLMultiError",
    "GraphQLClientHttpError",
    "GraphQlClientInvalidResponseError",
    "ModuleInformationInput",
    "ModuleInput",
    "ModuleMappingInput",
    "UpdateDegree",
    "UpdateDegreeUpdateDegree",
    "UpdateModule",
    "UpdateModuleUpdateModule",
    "UpdateModuleUpdateModuleInformationDe",
    "UpdateModuleUpdateModuleInformationEn",
]
