# Generated by ariadne-codegen on 2023-06-07 16:48
# Source: schema/queries.graphql

from typing import Optional

from .base_model import BaseModel


class GetModuleByID(BaseModel):
    module: Optional["GetModuleByIDModule"]


class GetModuleByIDModule(BaseModel):
    id: str
    number: str


GetModuleByID.update_forward_refs()
GetModuleByIDModule.update_forward_refs()
