# Generated by ariadne-codegen on 2023-06-07 10:25
# Source: schema/queries.graphql

from typing import Optional

from .base_model import BaseModel


class GetModuleByID(BaseModel):
    module: Optional["GetModuleByIDModule"]


class GetModuleByIDModule(BaseModel):
    id: str
    label: str
    information_en: Optional["GetModuleByIDModuleInformationEn"]
    information_de: Optional["GetModuleByIDModuleInformationDe"]


class GetModuleByIDModuleInformationEn(BaseModel):
    title: str
    number: str
    module_type: Optional[str]


class GetModuleByIDModuleInformationDe(BaseModel):
    title: str
    number: str
    module_type: Optional[str]


GetModuleByID.update_forward_refs()
GetModuleByIDModule.update_forward_refs()
GetModuleByIDModuleInformationEn.update_forward_refs()
GetModuleByIDModuleInformationDe.update_forward_refs()
