# Generated by ariadne-codegen on 2023-06-07 10:25
# Source: schema/queries.graphql

from typing import List, Optional

from .base_model import BaseModel


class GetDegreeByID(BaseModel):
    degree: Optional["GetDegreeByIDDegree"]


class GetDegreeByIDDegree(BaseModel):
    id: str
    number: str
    full_name_en: Optional[str]
    full_name_de: Optional[str]
    version: str
    modules: Optional[List[Optional["GetDegreeByIDDegreeModules"]]]


class GetDegreeByIDDegreeModules(BaseModel):
    module: "GetDegreeByIDDegreeModulesModule"
    version: str
    ects: int
    weighting_factor: float
    valid_from: str
    valid_until: Optional[str]


class GetDegreeByIDDegreeModulesModule(BaseModel):
    id: str
    label: str


GetDegreeByID.update_forward_refs()
GetDegreeByIDDegree.update_forward_refs()
GetDegreeByIDDegreeModules.update_forward_refs()
GetDegreeByIDDegreeModulesModule.update_forward_refs()
