# Generated by ariadne-codegen on 2023-06-07 10:25
# Source: schema/schema.graphql

from typing import List, Optional

from .base_model import BaseModel


class ModuleInformationInput(BaseModel):
    title: str
    number: str
    module_type: Optional[str]
    weekly_hours: Optional[int]
    offered_in: Optional[str]
    lecturers: Optional[List[Optional[str]]]
    organization: Optional[str]
    content: Optional[str]
    previous_knowledge: Optional[str]
    objective: Optional[str]
    language: Optional[str]
    lerning_method: Optional[str]
    workload: Optional[str]
    dates_url: Optional[str]
    recommended_reading: Optional[str]
    note: Optional[str]


class ModuleInput(BaseModel):
    id: str
    label: str
    information_en: Optional["ModuleInformationInput"]
    information_de: Optional["ModuleInformationInput"]


class ModuleMappingInput(BaseModel):
    module: "ModuleInput"
    version: str
    ects: int
    weighting_factor: float
    valid_from: str
    valid_until: Optional[str]


class DegreeInput(BaseModel):
    id: str
    number: str
    full_name_en: Optional[str]
    full_name_de: Optional[str]
    subtitle_en: Optional[str]
    subtitle_de: Optional[str]
    version: str
    modules: Optional[List[Optional["ModuleMappingInput"]]]


ModuleInformationInput.update_forward_refs()
ModuleInput.update_forward_refs()
ModuleMappingInput.update_forward_refs()
DegreeInput.update_forward_refs()
