# Generated by ariadne-codegen on 2023-06-07 16:48
# Source: schema/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateDegree(BaseModel):
    update_degree: Optional["UpdateDegreeUpdateDegree"] = Field(alias="updateDegree")


class UpdateDegreeUpdateDegree(BaseModel):
    id: str
    number: str
    full_name_en: Optional[str]
    full_name_de: Optional[str]
    version: str


UpdateDegree.update_forward_refs()
UpdateDegreeUpdateDegree.update_forward_refs()
