# Generated by ariadne-codegen on 2023-06-07 10:25
# Source: schema/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateModule(BaseModel):
    update_module: Optional["UpdateModuleUpdateModule"] = Field(alias="updateModule")


class UpdateModuleUpdateModule(BaseModel):
    id: str
    label: str
    information_en: Optional["UpdateModuleUpdateModuleInformationEn"]
    information_de: Optional["UpdateModuleUpdateModuleInformationDe"]


class UpdateModuleUpdateModuleInformationEn(BaseModel):
    title: str
    number: str
    module_type: Optional[str]


class UpdateModuleUpdateModuleInformationDe(BaseModel):
    title: str
    number: str
    module_type: Optional[str]


UpdateModule.update_forward_refs()
UpdateModuleUpdateModule.update_forward_refs()
UpdateModuleUpdateModuleInformationEn.update_forward_refs()
UpdateModuleUpdateModuleInformationDe.update_forward_refs()
